--STG
DROP TABLE ITDE1.RUBA_STG_ACCOUNTS;
DROP TABLE ITDE1.RUBA_STG_CARDS;
DROP TABLE ITDE1.RUBA_STG_CLIENTS;
DROP TABLE ITDE1.RUBA_STG_BLACKLIST;
DROP TABLE ITDE1.RUBA_STG_TERMINALS;
DROP TABLE ITDE1.RUBA_STG_TRANSACTIONS;

--DWH
DROP TABLE ITDE1.RUBA_DWH_DIM_ACCOUNTS_HIST;
DROP TABLE ITDE1.RUBA_DWH_DIM_CARDS_HIST;
DROP TABLE ITDE1.RUBA_DWH_DIM_CLIENTS_HIST;
DROP TABLE ITDE1.RUBA_DWH_FACT_BLACKLIST;
DROP TABLE ITDE1.RUBA_DWH_DIM_TERMINALS_HIST;
DROP TABLE ITDE1.RUBA_DWH_FACT_TRANSACTIONS;
DROP TABLE ITDE1.RUBA_REP_FRAUD;

--META
DROP TABLE ITDE1.RUBA_META_LOADING;