--STG
TRUNCATE TABLE ITDE1.RUBA_STG_ACCOUNTS;
TRUNCATE TABLE ITDE1.RUBA_STG_CARDS;
TRUNCATE TABLE ITDE1.RUBA_STG_CLIENTS;
TRUNCATE TABLE ITDE1.RUBA_STG_TERMINALS_RAW;

--DWH
TRUNCATE TABLE ITDE1.RUBA_DWH_DIM_ACCOUNTS_HIST;
TRUNCATE TABLE ITDE1.RUBA_DWH_DIM_CARDS_HIST;
TRUNCATE TABLE ITDE1.RUBA_DWH_DIM_CLIENTS_HIST;
TRUNCATE TABLE ITDE1.RUBA_DWH_FACT_BLACKLIST;
TRUNCATE TABLE ITDE1.RUBA_DWH_DIM_TERMINALS_HIST;
TRUNCATE TABLE ITDE1.RUBA_DWH_FACT_TRANSACTIONS;
TRUNCATE TABLE ITDE1.RUBA_REP_FRAUD;

--META
TRUNCATE TABLE ITDE1.RUBA_META_LOADING;